[package]
name = "RustUML"
version = "0.1.0"

authors = ["Moritz Withoeft <moritz_pit.withoeft@fh-bielefeld.de>, Valentin Hertel <valentin.hertel@fh-bielefeld.de"]

edition = "2018"

[dependencies]
rocket = "0.3.17"
rocket_codegen = "0.3.17"