[package]
name = "rust_uml"
version = "0.1.0"
authors = ["mwithoeft <moritz_pit.withoeft@fh-bielefeld.de>"]

[dependencies]
yew = {git = "https://github.com/DenisKolodin/yew"}
stdweb = "^0.4.9"
regex = "1"
svg = "0.5.11"
rusttype = "0.7.3"